name: CCUtilities
version: '1.0'
main: org.celestialcraft.cCUtilities.CCUtilities
api-version: '1.21'
website: https://celestialcraft.org
author: CelestialCraft
softdepend: [LuckPerms]

permissions:
  celestialpoints.admin:
    description: Allows admin commands for Celestial Points
    default: op

  celestial.admin:
    description: Allows reloading the plugin and using /celestial
    default: op

  entitymanager.use:
    description: Allows use of /entitymanager
    default: op

  customitems.unity:
    description: Allows use of Unity Item commands
    default: true

  rtp.use:
    description: Allows use of /wild, /nether, /end, and /rtp
    default: true

  customenderdragon.spawn:
    description: Allows spawning dragons manually with /ced spawn
    default: op

  customenderdragon.spawn.random:
    description: Allows using /ced spawn random
    default: op

  customenderdragon.kill:
    description: Allows killing the active dragon with /ced kill
    default: op

  customenderdragon.reload:
    description: Allows reloading the config with /ced reload
    default: op

  customenderdragon.timer:
    description: Allows checking the auto spawn timer with /ced timer
    default: true

  customenderdragon.fight:
    description: Allows teleporting to the active dragon fight with /ced fight
    default: true

  customenderdragon.clearisland:
    description: Allow /ced clearisland (clears non-player, non-XP entities on the End main island)
    default: op

  quests.use:
    description: Allows using the /quests command
    default: true

  quests.give:
    description: Allows giving quests to players
    default: op

  quests.reload:
    description: Allows reloading the quests config
    default: op

  quests.weekly:
    description: Allows claiming weekly quests
    default: true

  quests.claim:
    description: Allows claiming completed quests
    default: true

  quests.list:
    description: Allows listing active quests
    default: true

  celestialvoting.admin:
    description: Allows use of all CelestialVoting commands
    default: op

  celestialvoting.streak.others:
    description: Allows viewing other players' vote streaks
    default: op

  celestialvoting.streak:
    description: Allows viewing your own vote streak
    default: true

  ccutilities.rankselect.use:
    default: true
  ccutilities.rankselect.clear:
    default: true
  ccutilities.rankselect.star:
    default: true
  ccutilities.rankselect.architect:
    default: false
  ccutilities.rankselect.designer:
    default: false
  ccutilities.rankselect.ethereal:
    default: false
  ccutilities.rankselect.ascendant:
    default: false
  ccutilities.rankselect.radiant:
    default: false
  ccutilities.rankselect.heavenly:
    default: false
  ccutilities.rankselect.jupiter:
    default: false
  ccutilities.rankselect.saturn:
    default: false
  ccutilities.rankselect.neptune:
    default: false
  ccutilities.rankselect.earth:
    default: false
  ccutilities.rankselect.venus:
    default: false
  ccutilities.rankselect.mars:
    default: false
  ccutilities.rankselect.mercury:
    default: false
  ccutilities.rankselect.pluto:
    default: false

  shops.claim:
    description: Allows claiming a shop
    default: false
  shops.claim.ascendant:
    description: Allows claiming ascendant shop regions
    default: false
  shops.claim.saturn:
    description: Allows claiming saturn plots
    default: false
  shops.claim.divine:
    description: Allows claiming divine shop regions
    default: false
  shops.define:
    description: Allows defining shop regions (wand + /shops define)
    default: op
  shops.admin:
    description: Admin controls for shops (unclaim any shop, claim a shop for another player with /shops claim <username>)
    default: op
  shops.chest.bypass:
    description: Bypass shop chest and region protections
    default: op
  shops.info.admin:
    description: View extra shop info (e.g., type) with /shops info
    default: op

  # Maparts module permissions
  maparts.admin:
    description: Administer maparts (use /mapart wand & define, bypass entry lock, build/map creation bypass, manage any trust)
    default: op
  mapart.admin:
    description: Compatibility alias for maparts.admin
    default: op
    children:
      maparts.admin: true

  # Mapart claim count permissions (your command checks mapart.claim.<integer>)
  mapart.claim.1:
    description: Allows claiming up to 1 mapart platform
    default: false
  mapart.claim.2:
    description: Allows claiming up to 2 mapart platforms
    default: false
  mapart.claim.3:
    description: Allows claiming up to 3 mapart platforms
    default: false
  mapart.claim.4:
    description: Allows claiming up to 4 mapart platforms
    default: false
  mapart.claim.5:
    description: Allows claiming up to 5 mapart platforms
    default: false
  mapart.claim.6:
    description: Allows claiming up to 6 mapart platforms
    default: false
  mapart.claim.7:
    description: Allows claiming up to 7 mapart platforms
    default: false
  mapart.claim.8:
    description: Allows claiming up to 8 mapart platforms
    default: false
  mapart.claim.9:
    description: Allows claiming up to 9 mapart platforms
    default: false
  mapart.claim.10:
    description: Allows claiming up to 10 mapart platforms
    default: false
  maparts.use:
    description: Allows non-admin maparts actions (claim, trust, untrust, lock, info, trustlist, warp, setwarp)
    default: true

  celestial.backpack.use:
    description: Allows non-OPs to use /backpack
    default: op